import React, { Component } from "react";
import axios from 'axios';
import "bootstrap/dist/css/bootstrap.min.css"; // Import Bootstrap CSS
import "./EmployeeRegistrationForm.css"; // Create your custom CSS file for styling
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



class EmployeeRegistrationForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      empId: "", // Assuming empId is auto-generated by the server
      empName: "",
      empDept: "",
      empSalary: "",
    };
  }

  handleChange = (e) => {
    this.setState({
      [e.target.name]: e.target.value,
    });
  };

  handleSubmit = (event) => {
    event.preventDefault();

    const employeeData = {
      empId: this.state.empId,
      empName: this.state.empName,
      empDept: this.state.empDept,
      empSalary: this.state.empSalary,
    };

    axios.post('http://localhost:8081/api/employes', employeeData)
      .then((response) => {
        console.log('Registration successful', response.data);
        this.setState({
          empName: "",
          empDept: "",
          empSalary: "",
        });
        this.handleShowToast();
        setTimeout(() => {
          window.location.replace('http://localhost:3000/signup');
        }, 3000);
      })
      .catch((error) => {
        console.error('Registration failed', error);
        this.handleShowError();
      });
  }

  handleShowToast = () => {
    toast.success('Employee Registration Successful', {
      position: toast.POSITION.TOP_CENTER,
      autoClose: 15000,
    });
  }

  handleShowError = () => {
    toast.error('Employee Registration failed. Please try again.', {
      position: toast.POSITION.TOP_CENTER,
      autoClose: 3000,
    });
  }

  render() {
    return (
      <div className="container">
        <h2>Employee Registration Form</h2>
        <form onSubmit={this.handleSubmit}>
          <div className="form-group">
            <input
              type="text"
              className="form-control"
              name="empId"
              placeholder="Employee ID"
              value={this.state.empId}
              disabled // Disable the input field
            />
          </div>
          <div className="form-group">
            <input
              type="text"
              className="form-control"
              name="empName"
              placeholder="Employee Name"
              value={this.state.empName}
              onChange={this.handleChange}
              required
            />
          </div>
          <div className="form-group">
            <input
              type="text"
              className="form-control"
              name="empDept"
              placeholder="Employee Department"
              value={this.state.empDept}
              onChange={this.handleChange}
              required
            />
          </div>
          <div className="form-group">
            <input
              type="text"
              className="form-control"
              name="empSalary"
              placeholder="Employee Salary"
              value={this.state.empSalary}
              onChange={this.handleChange}
              required
            />
          </div>
          <ToastContainer />
          <button type="submit" className="btn btn-primary">
            Register
          </button>
        </form>
      </div>
    );
  }
}

export default EmployeeRegistrationForm;
